<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-BGD5SC2" ignored="1" name="Default test" tests="9" failures="2" timestamp="01 Apr 2022 15:10:21 GMT" time="11.437" errors="0">
  <testcase name="close" time="0.0" classname="com.flipkart.stepDefinition1.MobileValidation">
    <failure type="org.testng.TestNGException" message="
Parameter &amp;apos;username&amp;apos; is required by @Test on method close but has not been marked @Optional or defined
in C:\Users\Pavithra\AppData\Local\Temp\testng-eclipse--2121742088\testng-customsuite.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'username' is required by @Test on method close but has not been marked @Optional or defined
in C:\Users\Pavithra\AppData\Local\Temp\testng-eclipse--2121742088\testng-customsuite.xml
at org.testng.internal.Parameters.createParams(Parameters.java:290)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:359)
at org.testng.internal.Parameters.createParameters(Parameters.java:620)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- close -->
  <testcase name="search" time="0.196" classname="com.flipkart.stepDefinition1.MobileValidation"/>
  <testcase name="name" time="0.002" classname="com.flipkart.stepDefinition1.MobileValidation">
    <failure type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: name([])
Arguments: [(java.lang.String) realme]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: name([])
Arguments: [(java.lang.String) realme]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- name -->
  <testcase name="window" time="0.015" classname="com.flipkart.stepDefinition1.MobileValidation"/>
  <testcase name="Success" time="0.002" classname="com.flipkart.stepDefinition1.MobileValidation"/>
  <testcase name="Success" time="0.001" classname="com.flipkart.stepDefinition1.MobileValidation"/>
  <testcase name="Success" time="0.001" classname="com.flipkart.stepDefinition1.MobileValidation"/>
  <testcase name="Success" time="0.001" classname="com.flipkart.stepDefinition1.MobileValidation"/>
  <testcase name="Success" time="0.002" classname="com.flipkart.stepDefinition1.MobileValidation"/>
  <testcase name="validation" time="0.0" classname="com.flipkart.stepDefinition1.MobileValidation">
    <ignored/>
  </testcase> <!-- validation -->
</testsuite> <!-- Default test -->
